# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.0.7
_src_path: https://github.com/jupyterlab/extension-template
author_email: tony.hirst@gmail.com
author_name: Tony Hirst
has_binder: false
has_settings: true
kind: frontend
labextension_name: jupyterlab_empinken_extension
project_short_description: A JupyterLab extension.
python_name: jupyterlab_empinken_extension
repository: https://github.com/innovationOUtside/jupyterlab_empinken_extension
test: false

